global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]
  - job_name: "ml-analytics"
    static_configs:
      - targets: ["host.docker.internal:9108"]
